### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by Froffri** [just-hms/DM-ML#11]
- Pulizia rumore (e outlier) -> fare un boxplot / maybe clustering?
- Feature reduction -> PCA / Feature selection based on mutual information
- Data reduction (se serve) -> Sampling / Data aggregation / compression?
- Normalization -> min-max (attenti agli outlier) / z-score
- Discretization -> binning / histogram / clustering / decision-tree / chi2 analysis

**Comment by Froffri** [comment]
Continuare con gli istogrammi e con l'analisi cumulativa degli attributi scelti

**Comment by just-hms** [comment]
- remove `Label` from todrop
- merge similar attack class
- PCA
- check data distribution

**Comment by just-hms** [comment]
![image](https://user-images.githubusercontent.com/57114674/210583816-eaae3013-3948-4332-9424-0e7b01824f38.png)
