### ISSUE TITLE
Accuracy of multiclass model

### ISSUE THREAD

**Issue by Froffri** [just-hms/DM-ML#9]
- Filtrare la tabella in base alle label predette invece che quelle effettive per testare il caso più reale.

**Comment by just-hms** [comment]
🙃❤️

**Comment by just-hms** [comment]
- creare la label `non attacco` tra le classi di attacco in modo da fare la matrice di confusione finale anche nel problema multi-classe
- continuare a trainare il modello multi-classe solo sugli attacchi
- usare questa `pseudo-label` per avere la matrice di confusione finale in cui possiamo vedere l'accuratezza totale
